### ISSUE TITLE
Support L293DD?

### ISSUE THREAD

**Issue by samuk** [hadabot/hadabot_main#28]
I'm working on a version of this open hardware board to support encoder inputs: https://github.com/hansj66/micro-bot/#readme

To be used with a ESP32 feather https://github.com/rosmo-robot/Feather-Bit/tree/main/v1

Would Hadabot support L293DD motor driver?

**Comment by jschrier** [comment]
From the hardware perspective: The nominal hadabot kit uses a L9110 motor driver; the ESP 32 provides a PWM signal at 3.3 V to drive the left and right two motors via the L9110 driver.  IIRC, L293s need a 5V signal...so that might be a problem.

From the software perspective: The software just drives a PWM signal, so there's likely no change.

**Comment by samuk** [comment]
Great, we have a logic level shifter on board (TXB0106PWR)

I'll make a few boards and then have a go I guess.
